# Generated by Django 3.0.2 on 2020-02-03 21:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=datetime.datetime(2020, 2, 3, 21, 13, 51, 335586, tzinfo=utc), upload_to='img'),
            preserve_default=False,
        ),
    ]
