# Generated by Django 3.0.2 on 2020-02-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200203_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.TextField(default=None, max_length=60),
        ),
    ]
