# Generated by Django 3.0.1 on 2020-02-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='postc',
        ),
    ]
