# Generated by Django 3.0.1 on 2020-03-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_1', upload_to='post_pics'),
        ),
    ]
