# Generated by Django 3.0.1 on 2020-03-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200321_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_1.jpg', upload_to='post_pics'),
        ),
    ]
