# Generated by Django 3.0.1 on 2020-03-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200316_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
    ]
