# Generated by Django 3.0.1 on 2020-03-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200316_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(default='https://www.facebook.com/', max_length=100, null=True),
        ),
    ]
